# Generated by Django 4.2.9 on 2024-02-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://www.24kitchen.nl/files/styles/social_media_share/public/2019-02/shutterstock_230090839%20%281%29.jpg?itok=GqC27biB', max_length=500),
        ),
    ]
