# Generated by Django 4.2.9 on 2024-02-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_img',
            new_name='item_image',
        ),
    ]
