# Generated by Django 4.2.9 on 2024-02-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_item_img_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://theme-assets.getbento.com/sensei/bf9e806.sensei/assets/images/catering-item-placeholder-704x520.png', max_length=500),
        ),
    ]
