# Generated by Django 4.2.9 on 2024-02-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs',
        ),
        migrations.AddField(
            model_name='food',
            name='carbohydrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_fibre',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='sugars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
