# Generated by Django 4.2.9 on 2024-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0003_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0),
        ),
    ]
