# Generated by Django 4.2.9 on 2024-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
