# Generated by Django 4.2.9 on 2024-02-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='movies/images/default.jpg', upload_to='movies/images'),
        ),
    ]
